
service: time-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  status:
    handler: src/status/statusLambda.status
    events:
      - http:
          method: GET
          path: ifttt/v1/status
          cors: true
