
service: time-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2

functions:
  status:
    handler: src/ifttt/statusLambda.status
    events:
      - http:
          method: GET
          path: ifttt/v1/status
          cors: true
  verifyIdToken:
    handler: src/auth/authLambda.verifyIdToken
    events:
      - http:
          method: POST
          path: auth/verifyIdToken
          cors: true

resources:
  Resources:
    accessTokenTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accessTokenTableName}
        AttributeDefinitions:
          - AttributeName: accessToken
            AttributeType: S
        KeySchema:
          - AttributeName: accessToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    authorizationCodeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.authorizationCodeTableName}
        AttributeDefinitions:
          - AttributeName: authorizationCode
            AttributeType: S
        KeySchema:
          - AttributeName: authorizationCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    clientTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.clientTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    sessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.sessionTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
