
service: time-api

plugins:
  - serverless-secrets
  - serverless-webpack

custom:
  stage: ${opt:stage, self:provider.stage}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
  userTimerTableName: time-api-userTimer-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  environment:
    stage: ${self:custom.stage}
    userTimerTableName: ${self:custom.userTimerTableName}
  environmentSecrets:
    AUTH0_TIME_CERTIFICATE: /time-api/${self:custom.stage}/AUTH0_TIME_CERTIFICATE
    IFTTT_SERVICE_KEY: /time-api/${self:custom.stage}/IFTTT_SERVICE_KEY
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  status:
    handler: src/ifttt/iftttLambda.status
    events:
      - http:
          method: GET
          path: ifttt/v1/status
          cors: true
  userInfo:
    handler: src/ifttt/iftttLambda.userInfo
    events:
      - http:
          method: GET
          path: ifttt/v1/user/info
          cors: true
  timerStart:
    handler: src/ifttt/iftttLambda.timerStart
    events:
      - http:
          method: POST
          path: ifttt/v1/actions/timer_start
          cors: true
  getMyTimers:
    handler: src/timer/controller/timerLambda.getMyTimers
    events:
      - http:
          method: GET
          path: /timers
          cors: true

resources:
  Resources:
    userTimerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTimerTableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: timerId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: timerId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
