
# zsh

export ZSH=/root/.oh-my-zsh
ZSH_THEME="corey"
plugins=(
  git
)
source $ZSH/oh-my-zsh.sh

# nvm

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
