
prod:
  api:
    domain: time-api.overattribution.com
    allowOrigins:
      - https://time.overattribution.com
      - https://local.time.overattribution.com:8080

preprod:
  api:
    domain: time-api-dev.overattribution.com
    allowOrigins:
      - https://time.overattribution.com
      - https://local.time.overattribution.com:8080

test:
  api:
    domain: time-api-test.overattribution.com
    allowOrigins:
      - https://time-test.overattribution.com
      - https://time-test2.overattribution.com:3000
